"""Initialize xonsh.

Vim: set ft=python:

Mar 03, 2019:

Just got an error from the fzf widget.


Traceback (most recent call last):
  File "/data/data/com.termux/files/home/virtualenvs/xonsh/lib/python3.7/site-packages/xonsh/__amalgam__.py",

line 8459, in _call handler(**self _kwargs)

File "/data/data/com.termux/files/home/virtualenvs/xonsh/lib/python3.7/site-packages/xontrib/fzf-widgets.xsh",

line 56, in custom_keybindings handler('fzf_history_binding')

File "/data/data/com.termux/files/home/virtualenvs/xonsh/lib/python3.7/site-packages/xontrib/fzf-widgets.xsh",

line 53, in handler::

    >>> return bindings.registry.add_binding(key)

AttributeError: 'KeyBindings' object has no attribute 'registry'
Exception raised in event handler; ignored.

(xonsh) <user>@localhost ~ $
nvim "/data/data/com.termux/files/home/virtualenvs/xonsh/lib/python3.7/site-packages/xontrib/fzf-widgets.xsh"

Changing the line above to::

    >>> return bindings.add_binding(key)

Fixed it immediately. Just to take note of that.

"""
# XONSH WIZARD START
source-bash "echo loading xonsh foreign shell"
# XONSH WIZARD END

    # XONSH WIZARD START
$AUTO_SUGGEST_IN_COMPLETIONS = '1'
$CASE_SENSITIVE_COMPLETIONS = '1'

$DIRSTACK_SIZE = '100'

# Include hidden files when considering candidates for :mod:`xonsh.completer`
$DOTGLOB = '1'
$DYNAMIC_CWD_ELISION_CHAR = "'...'"
$DYNAMIC_CWD_WIDTH = '15.0'
$LANG = 'en_US.UTF-8'
$MULTILINE_PROMPT = '...'
$_PATH = "$PATH"
# $PATH = "['/home/faris/google-cloud-sdk/bin', '/home/faris/miniconda3/condabin', '/home/faris/.cargo/bin', '/home/faris/bin', '/home/faris/.local/bin', '/usr/local/sbin', '/usr/local/bin', '/usr/sbin', '/usr/bin', '/sbin', '/bin', '/usr/games', '/usr/local/games', '/snap/bin', '/home/faris/.rvm/bin', '/home/faris/.gem/ruby/2.5.0/bin', '/home/faris/.rvm/bin', '/home/faris/go/bin', '/home/faris/.yarn/bin', '/home/faris/.config/yarn/global/node_modules/.bin', '/home/faris/.racket/7.1/bin', '/home/faris/.rvm/bin', '/home/faris/.fzf/bin', '/home/faris/.rvm/bin']"

# ...wait how the hell did that get set on KDE Neon i can't run exe files
# $PATHEXT = "'.EXE'"
$PROMPT = '{user}@{hostname}:{cwd}$ '
$PROMPT_TOOLKIT_COLOR_DEPTH = 'DEPTH_24_BIT'
$VI_MODE = '1'
$XONSH_AUTOPAIR = '1'
$XONSH_CACHE_EVERYTHING = '1'
# $XONSH_GITSTATUS_* = 'default'
# $XONSH_HISTORY_SIZE = '107374182400 b'
$XONSH_HISTORY_SIZE = '107374182400'
$XONSH_SHOW_TRACEBACK = 'True'
$XONSH_STORE_STDIN = '1'
$XONSH_STORE_STDOUT = '1'
$XONSH_TRACEBACK_LOGFILE = '/home/faris/.local/share/xonsh/traceback.log'
# source-foreign --envcmd %env -p 'conda activate && ipython'
# xontrib load apt_tabcomplete base16_shell coreutils distributed jedi mpl prompt_ret_code xonda prompt_vi_mode
xontrib load jedi xonda bashisms
# XONSH WIZARD END
